run:
	@rm -rf work
	@python3 ../../../../src/redaction.py -t i2c_master_top -m output -n wb_dat_o timescale.v i2c_master_bit_ctrl.v  i2c_master_defines.v i2c_master_byte_ctrl.v  i2c_master_top.v

clean:
	@rm -rf work   