run:
	@rm -rf work
	@cd src; python3 ../../../../src/redaction.py -t des3 -m io+out+rank -r 1 -p 96 -n ../outfile crp.v des3.v key_sel3.v sbox1.v sbox2.v sbox3.v sbox4.v sbox5.v sbox6.v sbox7.v sbox8.v

clean:
	@rm -rf work
